title: Jack Facts
description: The trials and tribulations of a full stack application developer. 

# url: https://jack-facts.com/
url: http://localhost:4000/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: jackfacts
   twitter: jack-facts
   facebook: jacksondaw
   email: jacksondaw@gmail.com

sass:
  sass_dir: scss
  style: compressed

# google_analytics: "UA-58263416-1"
